### ISSUE TITLE
Investigate CSS file size [low priority]

### ISSUE THREAD

**Issue by codeTrackLift** [codepharm/motiv8m3#101]
Noticed that the two files listed below have over 11k lines of code.  Suggest to investigate and minimize file size.

[tacklePost.css](https://github.com/codepharm/motiv8m3/blob/main/styles/tacklePost.css)
[tackles.css](https://github.com/codepharm/motiv8m3/blob/main/styles/tackles.css)

Looks like it happened during [this commit](https://github.com/codepharm/motiv8m3/commit/3b9f838556d99878ba48db00b02ed83bfed47403)

**Comment by IsthisSid** [comment]
Removing these 2 files with ticket #104 
Will create new (trimmed) css file for the content

**Comment by IsthisSid** [comment]
Update:
- about.css, global.css, welcome.css, lifestyle.css has been trimmed and reviewed - see PR #110 
- investigate and trim journey.css 
- create navbar.css file
